version: "3.8"

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: builder
    ports:
      - "4000:4000"
    restart: always
    develop:
      watch:
        - action: rebuild
          target: .
          ignore:
            - .git
            - .github
            - .gitignore
            
